/* tslint:disable */
/* eslint-disable */
/**
 * free-ran-ue Console API
 * API documentation for free-ran-ue Console
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface ApiConsoleAuthenticatePost200Response
 */
export interface ApiConsoleAuthenticatePost200Response {
    /**
     * 
     * @type {string}
     * @memberof ApiConsoleAuthenticatePost200Response
     */
    'message'?: string;
}
/**
 * 
 * @export
 * @interface ApiConsoleAuthenticatePost401Response
 */
export interface ApiConsoleAuthenticatePost401Response {
    /**
     * 
     * @type {string}
     * @memberof ApiConsoleAuthenticatePost401Response
     */
    'message'?: string;
}
/**
 * 
 * @export
 * @interface ApiConsoleGnbInfoPost200Response
 */
export interface ApiConsoleGnbInfoPost200Response {
    /**
     * 
     * @type {string}
     * @memberof ApiConsoleGnbInfoPost200Response
     */
    'message'?: string;
    /**
     * 
     * @type {GnbInfo}
     * @memberof ApiConsoleGnbInfoPost200Response
     */
    'gnbInfo'?: GnbInfo;
}
/**
 * 
 * @export
 * @interface ApiConsoleGnbInfoPost400Response
 */
export interface ApiConsoleGnbInfoPost400Response {
    /**
     * 
     * @type {string}
     * @memberof ApiConsoleGnbInfoPost400Response
     */
    'message'?: string;
    /**
     * 
     * @type {EmptyGnbInfo}
     * @memberof ApiConsoleGnbInfoPost400Response
     */
    'gnbInfo'?: EmptyGnbInfo;
}
/**
 * 
 * @export
 * @interface ApiConsoleGnbInfoPost401Response
 */
export interface ApiConsoleGnbInfoPost401Response {
    /**
     * 
     * @type {string}
     * @memberof ApiConsoleGnbInfoPost401Response
     */
    'message'?: string;
    /**
     * 
     * @type {EmptyGnbInfo}
     * @memberof ApiConsoleGnbInfoPost401Response
     */
    'gnbInfo'?: EmptyGnbInfo;
}
/**
 * 
 * @export
 * @interface ApiConsoleGnbInfoPost500Response
 */
export interface ApiConsoleGnbInfoPost500Response {
    /**
     * 
     * @type {string}
     * @memberof ApiConsoleGnbInfoPost500Response
     */
    'message'?: string;
    /**
     * 
     * @type {EmptyGnbInfo}
     * @memberof ApiConsoleGnbInfoPost500Response
     */
    'gnbInfo'?: EmptyGnbInfo;
}
/**
 * 
 * @export
 * @interface ApiConsoleGnbInfoPostRequest
 */
export interface ApiConsoleGnbInfoPostRequest {
    /**
     * 
     * @type {string}
     * @memberof ApiConsoleGnbInfoPostRequest
     */
    'ip': string;
    /**
     * 
     * @type {number}
     * @memberof ApiConsoleGnbInfoPostRequest
     */
    'port': number;
}
/**
 * 
 * @export
 * @interface ApiConsoleGnbUeNrdcPost200Response
 */
export interface ApiConsoleGnbUeNrdcPost200Response {
    /**
     * 
     * @type {string}
     * @memberof ApiConsoleGnbUeNrdcPost200Response
     */
    'message'?: string;
}
/**
 * 
 * @export
 * @interface ApiConsoleGnbUeNrdcPost400Response
 */
export interface ApiConsoleGnbUeNrdcPost400Response {
    /**
     * 
     * @type {string}
     * @memberof ApiConsoleGnbUeNrdcPost400Response
     */
    'message'?: string;
}
/**
 * 
 * @export
 * @interface ApiConsoleGnbUeNrdcPost401Response
 */
export interface ApiConsoleGnbUeNrdcPost401Response {
    /**
     * 
     * @type {string}
     * @memberof ApiConsoleGnbUeNrdcPost401Response
     */
    'message'?: string;
}
/**
 * 
 * @export
 * @interface ApiConsoleGnbUeNrdcPost404Response
 */
export interface ApiConsoleGnbUeNrdcPost404Response {
    /**
     * 
     * @type {string}
     * @memberof ApiConsoleGnbUeNrdcPost404Response
     */
    'message'?: string;
}
/**
 * 
 * @export
 * @interface ApiConsoleGnbUeNrdcPost500Response
 */
export interface ApiConsoleGnbUeNrdcPost500Response {
    /**
     * 
     * @type {string}
     * @memberof ApiConsoleGnbUeNrdcPost500Response
     */
    'message'?: string;
}
/**
 * 
 * @export
 * @interface ApiConsoleGnbUeNrdcPostRequest
 */
export interface ApiConsoleGnbUeNrdcPostRequest {
    /**
     * 
     * @type {string}
     * @memberof ApiConsoleGnbUeNrdcPostRequest
     */
    'ip': string;
    /**
     * 
     * @type {number}
     * @memberof ApiConsoleGnbUeNrdcPostRequest
     */
    'port': number;
    /**
     * 
     * @type {string}
     * @memberof ApiConsoleGnbUeNrdcPostRequest
     */
    'imsi': string;
}
/**
 * 
 * @export
 * @interface ApiConsoleLoginPost200Response
 */
export interface ApiConsoleLoginPost200Response {
    /**
     * 
     * @type {string}
     * @memberof ApiConsoleLoginPost200Response
     */
    'message'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiConsoleLoginPost200Response
     */
    'token'?: string;
}
/**
 * 
 * @export
 * @interface ApiConsoleLoginPost400Response
 */
export interface ApiConsoleLoginPost400Response {
    /**
     * 
     * @type {string}
     * @memberof ApiConsoleLoginPost400Response
     */
    'message'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiConsoleLoginPost400Response
     */
    'token'?: string;
}
/**
 * 
 * @export
 * @interface ApiConsoleLoginPost401Response
 */
export interface ApiConsoleLoginPost401Response {
    /**
     * 
     * @type {string}
     * @memberof ApiConsoleLoginPost401Response
     */
    'message'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiConsoleLoginPost401Response
     */
    'token'?: string;
}
/**
 * 
 * @export
 * @interface ApiConsoleLoginPost500Response
 */
export interface ApiConsoleLoginPost500Response {
    /**
     * 
     * @type {string}
     * @memberof ApiConsoleLoginPost500Response
     */
    'message'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiConsoleLoginPost500Response
     */
    'token'?: string;
}
/**
 * 
 * @export
 * @interface ApiConsoleLoginPostRequest
 */
export interface ApiConsoleLoginPostRequest {
    /**
     * 
     * @type {string}
     * @memberof ApiConsoleLoginPostRequest
     */
    'username': string;
    /**
     * 
     * @type {string}
     * @memberof ApiConsoleLoginPostRequest
     */
    'password': string;
}
/**
 * 
 * @export
 * @interface ApiConsoleLogoutDelete200Response
 */
export interface ApiConsoleLogoutDelete200Response {
    /**
     * 
     * @type {string}
     * @memberof ApiConsoleLogoutDelete200Response
     */
    'message'?: string;
}
/**
 * 
 * @export
 * @interface EmptyGnbInfo
 */
export interface EmptyGnbInfo {
    /**
     * 
     * @type {string}
     * @memberof EmptyGnbInfo
     */
    'gnbId'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmptyGnbInfo
     */
    'gnbName'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmptyGnbInfo
     */
    'plmnId'?: string;
    /**
     * 
     * @type {EmptyGnbInfoSnssai}
     * @memberof EmptyGnbInfo
     */
    'snssai'?: EmptyGnbInfoSnssai;
    /**
     * 
     * @type {Array<RanUe>}
     * @memberof EmptyGnbInfo
     */
    'ranUeList'?: Array<RanUe>;
    /**
     * 
     * @type {Array<XnUe>}
     * @memberof EmptyGnbInfo
     */
    'xnUeList'?: Array<XnUe>;
}
/**
 * 
 * @export
 * @interface EmptyGnbInfoSnssai
 */
export interface EmptyGnbInfoSnssai {
    /**
     * 
     * @type {string}
     * @memberof EmptyGnbInfoSnssai
     */
    'sst'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmptyGnbInfoSnssai
     */
    'sd'?: string;
}
/**
 * 
 * @export
 * @interface GnbInfo
 */
export interface GnbInfo {
    /**
     * 
     * @type {string}
     * @memberof GnbInfo
     */
    'gnbId'?: string;
    /**
     * 
     * @type {string}
     * @memberof GnbInfo
     */
    'gnbName'?: string;
    /**
     * 
     * @type {string}
     * @memberof GnbInfo
     */
    'plmnId'?: string;
    /**
     * 
     * @type {Snssai}
     * @memberof GnbInfo
     */
    'snssai'?: Snssai;
    /**
     * 
     * @type {Array<RanUe>}
     * @memberof GnbInfo
     */
    'ranUeList'?: Array<RanUe>;
    /**
     * 
     * @type {Array<XnUe>}
     * @memberof GnbInfo
     */
    'xnUeList'?: Array<XnUe>;
}
/**
 * 
 * @export
 * @interface RanUe
 */
export interface RanUe {
    /**
     * 
     * @type {string}
     * @memberof RanUe
     */
    'imsi'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof RanUe
     */
    'nrdcIndicator'?: boolean;
}
/**
 * 
 * @export
 * @interface Snssai
 */
export interface Snssai {
    /**
     * 
     * @type {string}
     * @memberof Snssai
     */
    'sst'?: string;
    /**
     * 
     * @type {string}
     * @memberof Snssai
     */
    'sd'?: string;
}
/**
 * 
 * @export
 * @interface XnUe
 */
export interface XnUe {
    /**
     * 
     * @type {string}
     * @memberof XnUe
     */
    'imsi'?: string;
}

/**
 * AuthenticationApi - axios parameter creator
 * @export
 */
export const AuthenticationApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Validate JWT token
         * @summary Authenticate Token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiConsoleAuthenticatePost: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/console/authenticate`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Authenticate user and return JWT token
         * @summary User Login
         * @param {ApiConsoleLoginPostRequest} apiConsoleLoginPostRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiConsoleLoginPost: async (apiConsoleLoginPostRequest: ApiConsoleLoginPostRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'apiConsoleLoginPostRequest' is not null or undefined
            assertParamExists('apiConsoleLoginPost', 'apiConsoleLoginPostRequest', apiConsoleLoginPostRequest)
            const localVarPath = `/api/console/login`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(apiConsoleLoginPostRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Logout current user
         * @summary User Logout
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiConsoleLogoutDelete: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/console/logout`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AuthenticationApi - functional programming interface
 * @export
 */
export const AuthenticationApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AuthenticationApiAxiosParamCreator(configuration)
    return {
        /**
         * Validate JWT token
         * @summary Authenticate Token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiConsoleAuthenticatePost(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiConsoleAuthenticatePost200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiConsoleAuthenticatePost(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthenticationApi.apiConsoleAuthenticatePost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Authenticate user and return JWT token
         * @summary User Login
         * @param {ApiConsoleLoginPostRequest} apiConsoleLoginPostRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiConsoleLoginPost(apiConsoleLoginPostRequest: ApiConsoleLoginPostRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiConsoleLoginPost200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiConsoleLoginPost(apiConsoleLoginPostRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthenticationApi.apiConsoleLoginPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Logout current user
         * @summary User Logout
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiConsoleLogoutDelete(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiConsoleLogoutDelete200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiConsoleLogoutDelete(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthenticationApi.apiConsoleLogoutDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AuthenticationApi - factory interface
 * @export
 */
export const AuthenticationApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AuthenticationApiFp(configuration)
    return {
        /**
         * Validate JWT token
         * @summary Authenticate Token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiConsoleAuthenticatePost(options?: RawAxiosRequestConfig): AxiosPromise<ApiConsoleAuthenticatePost200Response> {
            return localVarFp.apiConsoleAuthenticatePost(options).then((request) => request(axios, basePath));
        },
        /**
         * Authenticate user and return JWT token
         * @summary User Login
         * @param {ApiConsoleLoginPostRequest} apiConsoleLoginPostRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiConsoleLoginPost(apiConsoleLoginPostRequest: ApiConsoleLoginPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiConsoleLoginPost200Response> {
            return localVarFp.apiConsoleLoginPost(apiConsoleLoginPostRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Logout current user
         * @summary User Logout
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiConsoleLogoutDelete(options?: RawAxiosRequestConfig): AxiosPromise<ApiConsoleLogoutDelete200Response> {
            return localVarFp.apiConsoleLogoutDelete(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AuthenticationApi - object-oriented interface
 * @export
 * @class AuthenticationApi
 * @extends {BaseAPI}
 */
export class AuthenticationApi extends BaseAPI {
    /**
     * Validate JWT token
     * @summary Authenticate Token
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthenticationApi
     */
    public apiConsoleAuthenticatePost(options?: RawAxiosRequestConfig) {
        return AuthenticationApiFp(this.configuration).apiConsoleAuthenticatePost(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Authenticate user and return JWT token
     * @summary User Login
     * @param {ApiConsoleLoginPostRequest} apiConsoleLoginPostRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthenticationApi
     */
    public apiConsoleLoginPost(apiConsoleLoginPostRequest: ApiConsoleLoginPostRequest, options?: RawAxiosRequestConfig) {
        return AuthenticationApiFp(this.configuration).apiConsoleLoginPost(apiConsoleLoginPostRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Logout current user
     * @summary User Logout
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthenticationApi
     */
    public apiConsoleLogoutDelete(options?: RawAxiosRequestConfig) {
        return AuthenticationApiFp(this.configuration).apiConsoleLogoutDelete(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * GNBApi - axios parameter creator
 * @export
 */
export const GNBApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Get gNB information with specified IP and port
         * @summary Get gNB Info
         * @param {ApiConsoleGnbInfoPostRequest} apiConsoleGnbInfoPostRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiConsoleGnbInfoPost: async (apiConsoleGnbInfoPostRequest: ApiConsoleGnbInfoPostRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'apiConsoleGnbInfoPostRequest' is not null or undefined
            assertParamExists('apiConsoleGnbInfoPost', 'apiConsoleGnbInfoPostRequest', apiConsoleGnbInfoPostRequest)
            const localVarPath = `/api/console/gnb/info`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(apiConsoleGnbInfoPostRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Modify the NRDC status of a specific UE
         * @summary Modify UE NRDC Status
         * @param {ApiConsoleGnbUeNrdcPostRequest} apiConsoleGnbUeNrdcPostRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiConsoleGnbUeNrdcPost: async (apiConsoleGnbUeNrdcPostRequest: ApiConsoleGnbUeNrdcPostRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'apiConsoleGnbUeNrdcPostRequest' is not null or undefined
            assertParamExists('apiConsoleGnbUeNrdcPost', 'apiConsoleGnbUeNrdcPostRequest', apiConsoleGnbUeNrdcPostRequest)
            const localVarPath = `/api/console/gnb/ue/nrdc`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(apiConsoleGnbUeNrdcPostRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * GNBApi - functional programming interface
 * @export
 */
export const GNBApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = GNBApiAxiosParamCreator(configuration)
    return {
        /**
         * Get gNB information with specified IP and port
         * @summary Get gNB Info
         * @param {ApiConsoleGnbInfoPostRequest} apiConsoleGnbInfoPostRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiConsoleGnbInfoPost(apiConsoleGnbInfoPostRequest: ApiConsoleGnbInfoPostRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiConsoleGnbInfoPost200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiConsoleGnbInfoPost(apiConsoleGnbInfoPostRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GNBApi.apiConsoleGnbInfoPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Modify the NRDC status of a specific UE
         * @summary Modify UE NRDC Status
         * @param {ApiConsoleGnbUeNrdcPostRequest} apiConsoleGnbUeNrdcPostRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiConsoleGnbUeNrdcPost(apiConsoleGnbUeNrdcPostRequest: ApiConsoleGnbUeNrdcPostRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiConsoleGnbUeNrdcPost200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiConsoleGnbUeNrdcPost(apiConsoleGnbUeNrdcPostRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GNBApi.apiConsoleGnbUeNrdcPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * GNBApi - factory interface
 * @export
 */
export const GNBApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = GNBApiFp(configuration)
    return {
        /**
         * Get gNB information with specified IP and port
         * @summary Get gNB Info
         * @param {ApiConsoleGnbInfoPostRequest} apiConsoleGnbInfoPostRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiConsoleGnbInfoPost(apiConsoleGnbInfoPostRequest: ApiConsoleGnbInfoPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiConsoleGnbInfoPost200Response> {
            return localVarFp.apiConsoleGnbInfoPost(apiConsoleGnbInfoPostRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Modify the NRDC status of a specific UE
         * @summary Modify UE NRDC Status
         * @param {ApiConsoleGnbUeNrdcPostRequest} apiConsoleGnbUeNrdcPostRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiConsoleGnbUeNrdcPost(apiConsoleGnbUeNrdcPostRequest: ApiConsoleGnbUeNrdcPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiConsoleGnbUeNrdcPost200Response> {
            return localVarFp.apiConsoleGnbUeNrdcPost(apiConsoleGnbUeNrdcPostRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * GNBApi - object-oriented interface
 * @export
 * @class GNBApi
 * @extends {BaseAPI}
 */
export class GNBApi extends BaseAPI {
    /**
     * Get gNB information with specified IP and port
     * @summary Get gNB Info
     * @param {ApiConsoleGnbInfoPostRequest} apiConsoleGnbInfoPostRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GNBApi
     */
    public apiConsoleGnbInfoPost(apiConsoleGnbInfoPostRequest: ApiConsoleGnbInfoPostRequest, options?: RawAxiosRequestConfig) {
        return GNBApiFp(this.configuration).apiConsoleGnbInfoPost(apiConsoleGnbInfoPostRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Modify the NRDC status of a specific UE
     * @summary Modify UE NRDC Status
     * @param {ApiConsoleGnbUeNrdcPostRequest} apiConsoleGnbUeNrdcPostRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GNBApi
     */
    public apiConsoleGnbUeNrdcPost(apiConsoleGnbUeNrdcPostRequest: ApiConsoleGnbUeNrdcPostRequest, options?: RawAxiosRequestConfig) {
        return GNBApiFp(this.configuration).apiConsoleGnbUeNrdcPost(apiConsoleGnbUeNrdcPostRequest, options).then((request) => request(this.axios, this.basePath));
    }
}



